<a href="https://colab.research.google.com/github/theboredman/Machine-Learning-Course/blob/main/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Template

## Importing the libraries

In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [15]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [16]:
print(x)

[['Italy' 'Male' 'Bachelor' 41.0 68000.0 720.0]
 ['Portugal' 'Female' 'Master' 33.0 49000.0 680.0]
 ['Netherlands' 'Male' 'PhD' 29.0 52000.0 700.0]
 ['Portugal' 'Female' 'Bachelor' 45.0 nan nan]
 ['Italy' 'Female' 'High School' 38.0 57000.0 750.0]
 ['Netherlands' 'Male' 'Bachelor' nan 61000.0 690.0]
 ['Portugal' 'Female' 'Master' 36.0 55000.0 730.0]
 ['Italy' 'Male' 'PhD' 44.0 72000.0 710.0]
 ['Netherlands' 'Female' 'Bachelor' 47.0 81000.0 nan]
 ['Portugal' 'Male' 'Master' 39.0 nan 700.0]]


In [17]:
print(y)

['Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes']


## Missing Data

In [18]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,3:6])
x[:,3:6] = imputer.transform(x[:,3:6])

In [19]:
print(x)

[['Italy' 'Male' 'Bachelor' 41.0 68000.0 720.0]
 ['Portugal' 'Female' 'Master' 33.0 49000.0 680.0]
 ['Netherlands' 'Male' 'PhD' 29.0 52000.0 700.0]
 ['Portugal' 'Female' 'Bachelor' 45.0 61875.0 710.0]
 ['Italy' 'Female' 'High School' 38.0 57000.0 750.0]
 ['Netherlands' 'Male' 'Bachelor' 39.111111111111114 61000.0 690.0]
 ['Portugal' 'Female' 'Master' 36.0 55000.0 730.0]
 ['Italy' 'Male' 'PhD' 44.0 72000.0 710.0]
 ['Netherlands' 'Female' 'Bachelor' 47.0 81000.0 710.0]
 ['Portugal' 'Male' 'Master' 39.0 61875.0 700.0]]


## Encoding Categorical data

## OnHotEncoding

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [21]:
print(x)

[[1.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 41.0 68000.0 720.0]
 [0.0 0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 33.0 49000.0 680.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 29.0 52000.0 700.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 45.0 61875.0 710.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 38.0 57000.0 750.0]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 39.111111111111114 61000.0 690.0]
 [0.0 0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 36.0 55000.0 730.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 44.0 72000.0 710.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 47.0 81000.0 710.0]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 39.0 61875.0 700.0]]


## Label Encoder

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [23]:
print(y)

[1 0 1 0 1 0 1 0 1 1]


## Splitting the dataset into the Training set and Test set

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [25]:
print(x_train)

[[0.0 0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 36.0 55000.0 730.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 38.0 57000.0 750.0]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 41.0 68000.0 720.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 45.0 61875.0 710.0]
 [0.0 0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 33.0 49000.0 680.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 44.0 72000.0 710.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 47.0 81000.0 710.0]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 39.111111111111114 61000.0 690.0]]


In [26]:
print(x_test)

[[0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 29.0 52000.0 700.0]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 39.0 61875.0 700.0]]


In [27]:
print(y_train)

[1 1 1 0 0 0 1 0]


In [28]:
print(y_test)

[1 1]


## Feature Scalling

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,9:] = sc.fit_transform(x_train[:,9:])
x_test[:,9:] = sc.transform(x_test[:,9:])

In [30]:
print(x_train)

[[0.0 0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 -0.9826752396615944
  -0.8482487309872694 0.8551861104941366]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 -0.5348738646259308
  -0.639046731822779 1.8325416653445785]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.1368281979275646
  0.5115642635819178 0.3665083330689157]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 1.0324309479988918
  -0.12911685885933388 -0.12216944435630524]
 [0.0 0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 -1.6543773022150898
  -1.4758547284807404 -1.588202776631968]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.80853026048106 0.9299682619108984
  -0.12216944435630524]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 1.4802323230345553
  1.871377258151105 -0.12216944435630524]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 -0.28609532293945034
  -0.2206427334937984 -1.099524999206747]]


In [31]:
print(x_test)

[[0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 -2.549980052286417
  -1.162051729734005 -0.6108472217815262]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 -0.310973177108099
  -0.12911685885933388 -0.6108472217815262]]
